version: '3'
services:
  broker:
    env_file:
      - .env
    container_name: mosquitto-container
    hostname: mosquitto
    image: eclipse-mosquitto
    ports:
      - "${MOSQUITTO_PORT}:1883"
    networks:
      - mqtt
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro

  sensors:
    container_name: sensCont
    hostname: sensors
    build:
      context: .  # Il contesto di build è la root del progetto
      dockerfile: ./sensors/Dockerfile
    volumes:
      - ./simulated_env:/app/env
    depends_on:
      - broker
    networks:
      - mqtt
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=${MOSQUITTO_PORT}

  #   actuators:
#     container_name: actCont
#     hostname: actuators
#     build:
#       context: .  # Il contesto di build è la root del progetto
#       dockerfile: ./actuators/Dockerfile
#     volumes:
#       - ./simulated_env:/app/env
#     depends_on:
#       - broker
#     networks:
#       - mqtt
#     environment:
#       - MQTT_BROKER=mosquitto
#       - MQTT_PORT=${MOSQUITTO_PORT}

#   manager:
#     container_name: managerCont
#     hostname: manager
#     build:
#       context: .  # Il contesto di build è la root del progetto
#       dockerfile: ./manager/Dockerfile
#     volumes:
#       - ./simulated_env:/app/env
#     depends_on:
#       - broker
#       - sensors
#       - actuators
#     networks:
#       - mqtt
#     environment:
#       - MQTT_BROKER=mosquitto
#       - MQTT_PORT=${MOSQUITTO_PORT}

  # Aggiungi Node-RED
  node-red:
    image: nodered/node-red
    container_name: node-red
    ports:
      - "1880:1880"  # Porta per l'interfaccia web di Node-RED
    volumes:
      - ./node-red-data:/data  # Salva i flussi di Node-RED
      - ./simulated_env:/app/env  # Monta il file env.json
    depends_on:
      - broker
    networks:
      - mqtt
    environment:
      - NODE_RED_ENABLE_PROJECTS=true
    restart: unless-stopped

networks:
  mqtt:
    driver: bridge

volumes:
  mosquitto_data:
  simulated_env:
  node-red-data: